# Funding options
github: [clrogon]  # Replace with your GitHub username
patreon: your_patreon_username
open_collective: your_collective_name
ko_fi: your_kofi_username
custom: ['https://your-donation-link.com']
